//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public string admin1 { get; set; }
    public string password { get; set; }
}

public partial class Discount
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Code { get; set; }
    public int Price { get; set; }
    public string BeginDate { get; set; }
    public string EndDate { get; set; }
}

public partial class Member
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Member()
    {
        this.OrderLists = new HashSet<OrderList>();
        this.MemberShippings = new HashSet<MemberShipping>();
        this.OrderDetails = new HashSet<OrderDetail>();
        this.MessageBoxes = new HashSet<MessageBox>();
    }

    public int MemberID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public System.DateTime JoinDate { get; set; }
    public Nullable<int> EDM { get; set; }
    public string Gender { get; set; }
    public Nullable<System.DateTime> BirthDate { get; set; }
    public string Remark { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderList> OrderLists { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MemberShipping> MemberShippings { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MessageBox> MessageBoxes { get; set; }
}

public partial class MemberShipping
{
    public int MemberID { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public int ID { get; set; }
    public string Email { get; set; }

    public virtual Member Member { get; set; }
}

public partial class MessageBox
{
    public int ID { get; set; }
    public Nullable<int> MemberID { get; set; }
    public string Title { get; set; }
    public string Message { get; set; }
    public string File { get; set; }
    public string Answer { get; set; }
    public string QDate { get; set; }
    public string ADate { get; set; }

    public virtual Member Member { get; set; }
}

public partial class OrderDetail
{
    public int ID { get; set; }
    public int MemberID { get; set; }
    public int ProductID { get; set; }
    public int OrderID { get; set; }
    public int Count { get; set; }
    public int Payment { get; set; }
    public int PickUp { get; set; }

    public virtual Member Member { get; set; }
    public virtual OrderList OrderList { get; set; }
    public virtual Product Product { get; set; }
}

public partial class OrderList
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OrderList()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
    }

    public int MemberID { get; set; }
    public int OrderID { get; set; }
    public string OrderDate { get; set; }
    public string ShippedDate { get; set; }
    public string ShipName { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string State { get; set; }
    public string DiscountName { get; set; }
    public Nullable<int> DiscountPrice { get; set; }

    public virtual Member Member { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
}

public partial class Payment
{
    public int Id { get; set; }
    public int OrderID { get; set; }
    public string cardNumber { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
    }

    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductCategory { get; set; }
    public int Price { get; set; }
    public int Count { get; set; }
    public string Color { get; set; }
    public string Tags { get; set; }
    public string ImageFile { get; set; }
    public string ProductDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
}
